# Generated by Django 4.2.15 on 2024-08-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_monthlybudget_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Income', 'verbose_name_plural': 'Income'},
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='current_savings',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='palceholder.img', upload_to='profile_pics'),
        ),
    ]
