# Generated by Django 4.2.15 on 2024-08-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_income_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='goal_date',
            field=models.DateField(),
        ),
    ]
