# Generated by Django 4.2.15 on 2024-08-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='current_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
